version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    expose:
      - "3306"
    networks:
      - intra
    volumes:
      - db:/var/lib/mysql
    tty: true
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - intra
    tty: true
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file:
        - .env
    volumes:
        - wp:/var/www/html
    expose: 
        - "9000"
    networks:
        - intra
    tty: true

volumes:
  db: #{}
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH_DB}

  wp: #{}
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH_WP}

networks:
  intra:
    driver: bridge
